export const ActionTypes = {
  SET_STUDENTS: "SET_STUDENTS",
  SET_PAGESIZE: "SET_PAGESIZE",
  SET_CURRENTPAGE: "SET_CURRENTPAGE",
  SET_TOTALPAGES: "SET_TOTALPAGES",
  SET_PAGENUMBERS: "SET_PAGENUMBERS",
  SET_ISLOADING: "SET_ISLOADING",
  SET_STUDENTDETAILS: "SET_STUDENTDETAILS",
  SET_UPDATESTUDENT: "SET_UPDATESTUDENT",
  SET_DELETESUCCESS: "SET_DELETESUCCESS",
};